name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Auto PR from ${{ github.ref }}"
          body: "Automated PR for changes made in ${{ github.ref }}"
