name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Create PR using GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          PR_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          gh pr create --base main --head $PR_BRANCH_NAME --title "Auto PR from $PR_BRANCH_NAME" --body "Automated PR for changes made in $PR_BRANCH_NAME" 
