name: Create PR on push

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        uses: actions/create-pull-request@1.19.0
        with:
          title: "New feature"
          body: "This PR adds a new feature."
          head: main