name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create PR using GitHub CLI
        run: |
          PR_BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo ${{ secrets.GITHUB_TOKEN }} | gh pr create --base main --head $PR_BRANCH_NAME --title "Auto PR from $PR_BRANCH_NAME" --body "Automated PR for changes made in $PR_BRANCH_NAME" --repo ${{ github.repository }} --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
