name: Enviar E-mail

on:
  push:
    branches:
      - main

jobs:
  enviar_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Enviar E-mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: papaction@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Email from github actions"
          to: sh4dbr@gmail.com
          from: papaction@gmail.com
          body: "Corpo do E-mail gerado pelo actions"
